version: '3.1'

# backend : 6100
# db : 6101

services:
  api:
    build: .
    container_name: api
    ports: 
      - "8888:8888"
  db:
    image: postgres:14.3-alpine
    container_name: db
    ports:
      - "6101:6101"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    command:
      - "postgres"
      - "-c"
      - "port=6101"
    volumes:
      - pg:/var/lib/postgresql/data/

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8000:8080"
  #   container_name: adminer

  


volumes:
  pg: